'use client'; // Required in Next.js App Router for using hooks
import { ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import { createTheme } from '@mui/material/styles';
import './global.css';
import type { AppProps } from 'next/app';
import { Poppins } from 'next/font/google';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700'], // Choose weights as needed
  variable: '--font-poppins', // Optional: Set a CSS variable
});

// // Import your MFEs' lifecycle methods
// const mfe1next = () => import('@mfe-next'); // Update path to your MFE
// const mfe2next = () => import('@mfe-next-2'); // Update path to your MFE

/*export const metadata = {
  title: 'Welcome to shikshav2.0',
  description: 'Generated by create-nx-workspace',
};*/

const theme = createTheme({
  palette: {
    primary: {
      main: '#0E28AE',
    },
    secondary: {
      main: '#FFBD0D',
    },
    text: {
      secondary: 'grey',
    },
    mode: 'light', // or "dark"
  },
  typography: {
    fontFamily: 'var(--font-poppins), Arial, sans-serif',
  },
});

export default function RootLayout({ Component, pageProps }: AppProps) {
  console.log('hello');
  return (
    <ThemeProvider theme={theme}>
      <CssBaseline /> {/* Normalize styles */}
      <Component {...pageProps} />
    </ThemeProvider>
  );
}
