'use client';

import './global.css';

import { HashRouter } from 'react-router-dom';

// export const metadata = {
//   title: 'Welcome to mfe-next-2',
//   description: 'Generated by create-nx-workspace',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <HashRouter>{children}</HashRouter>
      </body>
    </html>
  );
}
