export const LANGUAGES = {
  ENGLISH: 'en',
  HINDI: 'hi',
} as const;

export const LANGUAGE_LABELS = {
  [LANGUAGES.ENGLISH]: 'English',
  [LANGUAGES.HINDI]: 'हिंदी',
} as const;

export const DEFAULT_LANGUAGE = LANGUAGES.ENGLISH;

export const SUPPORTED_LANGUAGES = [
  LANGUAGES.ENGLISH,
  LANGUAGES.HINDI,
] as const;

// Add a function to get the initial language
export const getInitialLanguage = () => {
  if (typeof window === 'undefined') return DEFAULT_LANGUAGE;

  // Always set English as default if no language is selected
  const savedLanguage = localStorage.getItem('selectedLanguage');
  if (!savedLanguage) {
    localStorage.setItem('selectedLanguage', DEFAULT_LANGUAGE);
    return DEFAULT_LANGUAGE;
  }

  // Validate saved language
  if (
    SUPPORTED_LANGUAGES.includes(
      savedLanguage as (typeof SUPPORTED_LANGUAGES)[number]
    )
  ) {
    return savedLanguage;
  }

  // Reset to English if invalid language is found
  localStorage.setItem('selectedLanguage', DEFAULT_LANGUAGE);
  return DEFAULT_LANGUAGE;
};

// Add a function to synchronize language across pages
export const synchronizeLanguage = (newLanguage: string) => {
  if (typeof window === 'undefined') return;

  // Validate language
  if (
    !SUPPORTED_LANGUAGES.includes(
      newLanguage as (typeof SUPPORTED_LANGUAGES)[number]
    )
  ) {
    newLanguage = DEFAULT_LANGUAGE;
  }

  // Update localStorage
  localStorage.setItem('selectedLanguage', newLanguage);

  // Update HTML lang attribute
  document.documentElement.lang = newLanguage;

  // Dispatch event for other tabs/windows
  window.dispatchEvent(
    new StorageEvent('storage', {
      key: 'selectedLanguage',
      newValue: newLanguage,
      storageArea: localStorage,
    })
  );
};

export const LANGUAGE_KEYS = {
  // Common
  SELECT_LANGUAGE: 'SELECT_LANGUAGE',
  LANGUAGE: 'LANGUAGE',

  // Auth
  SIGN_IN: 'SIGN_IN',
  REGISTER: 'REGISTER',
  EMAIL: 'EMAIL',
  PASSWORD: 'PASSWORD',
  CONFIRM_PASSWORD: 'CONFIRM_PASSWORD',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  REMEMBER_ME: 'REMEMBER_ME',
  DONT_HAVE_ACCOUNT: 'DONT_HAVE_ACCOUNT',
  ALREADY_HAVE_ACCOUNT: 'ALREADY_HAVE_ACCOUNT',
  USERNAME: 'USERNAME',
  SIGN_UP_LOGIN: 'SIGN_UP_LOGIN',
  PROCEED: 'PROCEED',
  GOOGLE_LOGIN: 'GOOGLE_LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  ACCOUNT_DELETED: 'ACCOUNT_DELETED',
  ERROR_OCCURRED: 'ERROR_OCCURRED',
  REQUIRED_FIELD: 'REQUIRED_FIELD',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_PASSWORD: 'INVALID_PASSWORD',

  // Registration
  FULL_NAME: 'FULL_NAME',
  EMAIL_ID: 'EMAIL_ID',
  MOBILE_NUMBER: 'MOBILE_NUMBER',
  GENDER: 'GENDER',
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  OTHER: 'OTHER',
  SELECT_GENDER: 'SELECT_GENDER',
  SELECT_ROLE: 'SELECT_ROLE',
  TERMS_AND_CONDITIONS: 'TERMS_AND_CONDITIONS',
  ACCEPT_TERMS: 'ACCEPT_TERMS',
  VERIFY_PROCEED: 'VERIFY_PROCEED',
  REGISTRATION_SUCCESS: 'REGISTRATION_SUCCESS',
  INVALID_NAME: 'INVALID_NAME',
  INVALID_MOBILE: 'INVALID_MOBILE',
  PASSWORD_REQUIREMENTS: 'PASSWORD_REQUIREMENTS',

  // Forgot Password Flow
  FORGOT_PASSWORD_TITLE: 'FORGOT_PASSWORD_TITLE',
  FORGOT_PASSWORD_SUBTITLE: 'FORGOT_PASSWORD_SUBTITLE',
  FORGOT_PASSWORD_DESCRIPTION: 'FORGOT_PASSWORD_DESCRIPTION',
  FORGOT_PASSWORD_EMAIL_LABEL: 'FORGOT_PASSWORD_EMAIL_LABEL',
  FORGOT_PASSWORD_EMAIL_PLACEHOLDER: 'FORGOT_PASSWORD_EMAIL_PLACEHOLDER',
  FORGOT_PASSWORD_SUBMIT: 'FORGOT_PASSWORD_SUBMIT',
  FORGOT_PASSWORD_BACK: 'FORGOT_PASSWORD_BACK',
  FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
  FORGOT_PASSWORD_SUCCESS_DESC: 'FORGOT_PASSWORD_SUCCESS_DESC',
  FORGOT_PASSWORD_ERROR: 'FORGOT_PASSWORD_ERROR',
  FORGOT_PASSWORD_ERROR_DESC: 'FORGOT_PASSWORD_ERROR_DESC',
  FORGOT_PASSWORD_INVALID_EMAIL: 'FORGOT_PASSWORD_INVALID_EMAIL',
  FORGOT_PASSWORD_EMAIL_NOT_FOUND: 'FORGOT_PASSWORD_EMAIL_NOT_FOUND',
  FORGOT_PASSWORD_TOO_MANY_REQUESTS: 'FORGOT_PASSWORD_TOO_MANY_REQUESTS',
  RESEND_CODE_IN: 'RESEND_CODE_IN',
  RESEND_CODE: 'RESEND_CODE',
  ATTEMPTS_REMAINING: 'ATTEMPTS_REMAINING',

  // Reset Password Flow
  RESET_PASSWORD_TITLE: 'RESET_PASSWORD_TITLE',
  RESET_PASSWORD_SUBTITLE: 'RESET_PASSWORD_SUBTITLE',
  RESET_PASSWORD_NEW_PASSWORD: 'RESET_PASSWORD_NEW_PASSWORD',
  RESET_PASSWORD_CONFIRM_PASSWORD: 'RESET_PASSWORD_CONFIRM_PASSWORD',
  RESET_PASSWORD_SUBMIT: 'RESET_PASSWORD_SUBMIT',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_SUCCESS_DESC: 'RESET_PASSWORD_SUCCESS_DESC',
  RESET_PASSWORD_ERROR: 'RESET_PASSWORD_ERROR',
  RESET_PASSWORD_ERROR_DESC: 'RESET_PASSWORD_ERROR_DESC',
  RESET_PASSWORD_LINK_EXPIRED: 'RESET_PASSWORD_LINK_EXPIRED',
  RESET_PASSWORD_LINK_EXPIRED_DESC: 'RESET_PASSWORD_LINK_EXPIRED_DESC',
  RESET_PASSWORD_INVALID_LINK: 'RESET_PASSWORD_INVALID_LINK',
  RESET_PASSWORD_INVALID_LINK_DESC: 'RESET_PASSWORD_INVALID_LINK_DESC',
  RESET_PASSWORD_MISMATCH: 'RESET_PASSWORD_MISMATCH',
  RESET_PASSWORD_REQUIREMENTS: 'RESET_PASSWORD_REQUIREMENTS',

  // Landing Page
  WELCOME_MESSAGE: 'WELCOME_MESSAGE',
  MISSION_STATEMENT: 'MISSION_STATEMENT',
  CHANGE_STEM: 'CHANGE_STEM',
  RESOURCES: 'RESOURCES',
  CATEGORIES: 'CATEGORIES',
  LANGUAGES_COUNT: 'LANGUAGES_COUNT',
  FOLLOW_INSTAGRAM: 'FOLLOW_INSTAGRAM',
  DIGITAL_HUB_BANNER: 'DIGITAL_HUB_BANNER',

  // Home Page
  BROWSE_SUBCATEGORIES: 'BROWSE_SUBCATEGORIES',
  BOOKMARKED_CONTENT: 'BOOKMARKED_CONTENT',
  NO_RESOURCES: 'NO_RESOURCES',
  RECOMMEND_HERE: 'RECOMMEND_HERE',
  FULL_ACCESS: 'FULL_ACCESS',
  ALL_ACCESS: 'ALL_ACCESS',

  // Messages
  LOGIN_REQUIRED: 'LOGIN_REQUIRED',
  FOOTER_TEXT_PART1: 'FOOTER_TEXT_PART1',
  FOOTER_TEXT_PART2: 'FOOTER_TEXT_PART2',

  // About Us
  SNAIL_TITLE: 'SNAIL_TITLE',
  SNAIL_SUBTITLE: 'SNAIL_SUBTITLE',
  SNAIL_DESCRIPTION: 'SNAIL_DESCRIPTION',
  SNAIL_VISION: 'SNAIL_VISION',
  SNAIL_REPOSITORY: 'SNAIL_REPOSITORY',
  SNAIL_EXPLORE: 'SNAIL_EXPLORE',
  SNAIL_CONTRIBUTE: 'SNAIL_CONTRIBUTE',
  LEADERSHIP_SUPPORT: 'LEADERSHIP_SUPPORT',
  LEADERSHIP_SUPPORT_CONTENT: 'LEADERSHIP_SUPPORT_CONTENT',
  TEAM: 'TEAM',
  TEAM_CONTENT: 'TEAM_CONTENT',
  ACKNOWLEDGMENTS: 'ACKNOWLEDGMENTS',
  ACKNOWLEDGMENTS_INTRO: 'ACKNOWLEDGMENTS_INTRO',
  FUNDING_SUPPORT: 'FUNDING_SUPPORT',
  FUNDING_SUPPORT_CONTENT: 'FUNDING_SUPPORT_CONTENT',
  TECHNICAL_SUPPORT: 'TECHNICAL_SUPPORT',
  TECHNICAL_SUPPORT_CONTENT: 'TECHNICAL_SUPPORT_CONTENT',
  CONTENT_SUPPORT: 'CONTENT_SUPPORT',
  CONTENT_SUPPORT_CONTENT: 'CONTENT_SUPPORT_CONTENT',
  CONTACT_US: 'CONTACT_US',
  CONTACT_ADDRESS: 'CONTACT_ADDRESS',
  CONTACT_PHONE: 'CONTACT_PHONE',
  CONTACT_EMAIL: 'CONTACT_EMAIL',
  CONTACT_WEBSITE: 'CONTACT_WEBSITE',

  // Terms and Conditions
  TERMS_TITLE: 'TERMS_TITLE',
  TERMS_WELCOME: 'TERMS_WELCOME',
  TERMS_CONTACT: 'TERMS_CONTACT',
  TERMS_LOGIN_TITLE: 'TERMS_LOGIN_TITLE',
  TERMS_LOGIN_CONTENT: 'TERMS_LOGIN_CONTENT',
  TERMS_TERMINATION_TITLE: 'TERMS_TERMINATION_TITLE',
  TERMS_TERMINATION_CONTENT: 'TERMS_TERMINATION_CONTENT',
  TERMS_CONTENT_IP_TITLE: 'TERMS_CONTENT_IP_TITLE',
  TERMS_CONTENT_IP_CONTENT: 'TERMS_CONTENT_IP_CONTENT',
  TERMS_COPYRIGHT_TITLE: 'TERMS_COPYRIGHT_TITLE',
  TERMS_COPYRIGHT_CONTENT: 'TERMS_COPYRIGHT_CONTENT',
  TERMS_USER_COMMUNITY_TITLE: 'TERMS_USER_COMMUNITY_TITLE',
  TERMS_USER_COMMUNITY_CONTENT: 'TERMS_USER_COMMUNITY_CONTENT',
  TERMS_PRIVACY_TITLE: 'TERMS_PRIVACY_TITLE',
  TERMS_PRIVACY_CONTENT: 'TERMS_PRIVACY_CONTENT',
  TERMS_DATA_TITLE: 'TERMS_DATA_TITLE',
  TERMS_DATA_CONTENT: 'TERMS_DATA_CONTENT',
  TERMS_COOKIES_TITLE: 'TERMS_COOKIES_TITLE',
  TERMS_COOKIES_CONTENT: 'TERMS_COOKIES_CONTENT',
  TERMS_CHILDREN_TITLE: 'TERMS_CHILDREN_TITLE',
  TERMS_CHILDREN_CONTENT: 'TERMS_CHILDREN_CONTENT',
  TERMS_OTHER_WEBSITES_TITLE: 'TERMS_OTHER_WEBSITES_TITLE',
  TERMS_OTHER_WEBSITES_CONTENT: 'TERMS_OTHER_WEBSITES_CONTENT',
  TERMS_DISCLOSURE_TITLE: 'TERMS_DISCLOSURE_TITLE',
  TERMS_DISCLOSURE_CONTENT: 'TERMS_DISCLOSURE_CONTENT',
  TERMS_GENERAL_READERS_TITLE: 'TERMS_GENERAL_READERS_TITLE',
  TERMS_GENERAL_READERS_CONTENT: 'TERMS_GENERAL_READERS_CONTENT',
  TERMS_LOGGED_READERS_TITLE: 'TERMS_LOGGED_READERS_TITLE',
  TERMS_LOGGED_READERS_CONTENT: 'TERMS_LOGGED_READERS_CONTENT',
  TERMS_RIGHTS_TITLE: 'TERMS_RIGHTS_TITLE',
  TERMS_RIGHTS_CONTENT: 'TERMS_RIGHTS_CONTENT',

  // Filter Dialog
  RESOURCE_TYPE_TITLE: 'RESOURCE_TYPE_TITLE',
  APPLY_BUTTON: 'APPLY_BUTTON',

  // Drawer Items
  HOME: 'HOME',
  LOGIN: 'LOGIN',
  ABOUT_US: 'ABOUT_US',
  RECOMMEND_RESOURCES: 'RECOMMEND_RESOURCES',
  // TERMS_AND_CONDITIONS: 'TERMS_AND_CONDITIONS',
  BOOKMARK: 'BOOKMARK',
  LOGOUT: 'LOGOUT',

  // Filter Dialog
  RESOURCE_TYPE: 'RESOURCE_TYPE',
  APPLY: 'APPLY',
  RESET: 'RESET',
  SUBJECT: 'SUBJECT',
  CONTENT_TYPE: 'CONTENT_TYPE',

  // Resource Types
  FICTION: 'FICTION',
  NON_FICTION: 'NON_FICTION',
  PICTURE_BOOK: 'PICTURE_BOOK',
  TEXTBOOK_CHAPTER: 'TEXTBOOK_CHAPTER',
  FIELD_GUIDE: 'FIELD_GUIDE',
  ACTIVITY_BOOK: 'ACTIVITY_BOOK',
  COMIC_BOOK: 'COMIC_BOOK',
  REFERENCE_BOOK: 'REFERENCE_BOOK',
  WEBSITE: 'WEBSITE',
  MAGAZINE: 'MAGAZINE',
  POSTER: 'POSTER',
  BOARD_GAME: 'BOARD_GAME',
  VIDEO: 'VIDEO',
  VIDEOS: 'VIDEOS',
  PDF: 'PDF',

  // Category Names
  WATER: 'WATER',
  LAND: 'LAND',
  FOREST: 'FOREST',
  CLIMATE_CHANGE: 'CLIMATE_CHANGE',
  ACTIVITY_BOOKS: 'ACTIVITY_BOOKS',
  REFERENCE_BOOKS: 'REFERENCE_BOOKS',
  GENERAL: 'GENERAL',
  POTPOURRI: 'POTPOURRI',

  // Subcategory Names
  WATER_BASED_STEM_ACTIVITIES: 'WATER_BASED_STEM_ACTIVITIES',
  WATER_BASIC_CONCEPTS: 'WATER_BASIC_CONCEPTS',
  WATER_BIODIVERSITY: 'WATER_BIODIVERSITY',
  WATER_CONSERVATION: 'WATER_CONSERVATION',
  WATER_AND_SANITATION: 'WATER_AND_SANITATION',
  WATER_CRISIS: 'WATER_CRISIS',
  FRESH_WATER_ECOSYSTEM: 'FRESH_WATER_ECOSYSTEM',
  COASTAL_ECOSYSTEM: 'COASTAL_ECOSYSTEM',
  WATER_BASED_STEM_AND_STEM_ACTIVITIES: 'WATER_BASED_STEM_AND_STEM_ACTIVITIES',
  GRASSLANDS: 'GRASSLANDS',
  GRASSLAND: 'GRASSLAND',
  MAGAZINES_NEWSPAPERS_WEBSITES: 'MAGAZINES_NEWSPAPERS_WEBSITES',
  MAGAZINES_NEWSPAPERS_AND_WEBSITIES: 'MAGAZINES_NEWSPAPERS_AND_WEBSITIES',
  FOREST_ECOSYSTEMS: 'FOREST_ECOSYSTEMS',
  CLIMATE_IMPACTS: 'CLIMATE_IMPACTS',
  ACTIVITY_WORKBOOKS: 'ACTIVITY_WORKBOOKS',
  REFERENCE_MATERIALS: 'REFERENCE_MATERIALS',
  GENERAL_TOPICS: 'GENERAL_TOPICS',
  MIXED_CONTENT: 'MIXED_CONTENT',
  SEED: 'SEED',
  PLANTS_AND_VEGETABLES: 'PLANTS_AND_VEGETABLES',
  AGRICULTURE: 'AGRICULTURE',
  FOOD_AND_WASTE: 'FOOD_AND_WASTE',
  SOIL: 'SOIL',
  LAND_BIODIVERSITY: 'LAND_BIODIVERSITY',
  ACTIVITY_BOOK_ON_KITCHEN_GARDENS: 'ACTIVITY_BOOK_ON_KITCHEN_GARDENS',
  TREES: 'TREES',
  PEOPLE: 'PEOPLE',
  WILDLIFE: 'WILDLIFE',
  FOREST_BIODIVERSITY: 'FOREST_BIODIVERSITY',
  FOREST_MANAGEMENT: 'FOREST_MANAGEMENT',
  FICTION_AND_NON_FICTION: 'FICTION_AND_NON_FICTION',
  LESSON_PLAN: 'LESSON_PLAN',
  CURRICULUM: 'CURRICULUM',

  // Search Dialog
  SEARCH_BY: 'SEARCH_BY',
  SEARCH_BUTTON: 'SEARCH_BUTTON',
  SEARCH_BY_AUTHOR: 'SEARCH_BY_AUTHOR',
  SEARCH_BY_PUBLISHER: 'SEARCH_BY_PUBLISHER',
  SEARCH_BY_LANGUAGE: 'SEARCH_BY_LANGUAGE',
  FIND_CONTENT_BY_CATEGORY: 'FIND_CONTENT_BY_CATEGORY',
  NO_RESULTS_FOUND: 'NO_RESULTS_FOUND',
  SHOWING_RESULTS_FOR: 'SHOWING_RESULTS_FOR',

  // Bookmark Messages
  BOOKMARK_ADDED_SUCCESS: 'BOOKMARK_ADDED_SUCCESS',
  BOOKMARK_REMOVED_SUCCESS: 'BOOKMARK_REMOVED_SUCCESS',
  BOOKMARK_ERROR: 'BOOKMARK_ERROR',
  PLEASE_LOGIN_TO_ACCESS_BOOKMARK: 'PLEASE_LOGIN_TO_ACCESS_BOOKMARK',
  LOGIN_REQUIRED_FOR_BOOKMARK: 'LOGIN_REQUIRED_FOR_BOOKMARK',

  // Content Page
  BROWSE_BY_SUB_CATEGORIES: 'BROWSE_BY_SUB_CATEGORIES',
  PREVIEW: 'PREVIEW',
  DOWNLOAD: 'DOWNLOAD',
  RESOURCE_LINK: 'RESOURCE_LINK',
  AUTHOR: 'AUTHOR',
  PUBLISHER: 'PUBLISHER',
  RELATED_CONTENT: 'RELATED_CONTENT',
  MORE_KEYWORDS: 'MORE_KEYWORDS',
  CLOSE: 'CLOSE',
  MESSAGE: 'MESSAGE',
  LOADING_TRANSLATIONS: 'LOADING_TRANSLATIONS',

  // Share Dialog
  SHARE_THIS_PAGE: 'SHARE_THIS_PAGE',
  COPY_LINK: 'COPY_LINK',
  COPIED: 'COPIED',

  // Login Dialog
  PLEASE_LOGIN_TO_CONTINUE: 'PLEASE_LOGIN_TO_CONTINUE',
} as const;

export type LanguageKey = keyof typeof LANGUAGE_KEYS;
